/**
 * Created by liuxun on 16/11/10.
 */
const SITE_STATE_UNACTIVE = "未激活";
const SITE_STATE_NORMAL = "正常";
const SITE_STATE_LOCK = "锁定";

const TABLE_CATEGORY_NORMAL = "normal";
const TABLE_CATEGORY_WITHOPTION = "option";

global.CONST = {
    SITE_STATE_UNACTIVE:SITE_STATE_UNACTIVE,
    SITE_STATE_NORMAL:SITE_STATE_NORMAL,
    SITE_STATE_LOCK:SITE_STATE_LOCK,

    TABLE_CATEGORY_NORMAL:TABLE_CATEGORY_NORMAL,
    TABLE_CATEGORY_WITHOPTION:TABLE_CATEGORY_WITHOPTION
};

//ResultCode
global.RESULT_CODE_SUCCESS = 1;
global.RESULT_CODE_DBERROR = 2;
global.RESULT_CODE_NOTFOUND = 3;
